### PR TITLE
TRITON-1943 add Jenkinsfiles to Triton repositories

### PR DESCRIPTION
**Pull request by cburroughs**

### CODE REVIEW

**Comment by trentm** [comment]
This failed in the *build* stage:

```
...
00:05:08.028  	-t PR-5-20191018T193922Z-g0b0a99d-dirty
00:05:08.028  bits-upload.sh: error: Bits timestamp PR-5-20191018T193922Z-g0b0a99d-dirty marked 'dirty': not uploading
00:05:08.028  bits-upload.sh: error: error exit status 1 at line 1
00:05:08.028  make: *** [deps/eng/tools/mk/Makefile.targ:537: bits-upload] Error 1
```

wassup with that I wonder... and why different from https://jenkins.joyent.us/job/dhcpd/ builds?

**Comment by trentm** [comment]
That "dirty" is this:

```
[root@07e90b99 ~/data/jenkins/workspace/joyent-org_sdc-booter_PR-5]# git status
On branch PR-5
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```

and

```
[root@07e90b99 ~/data/jenkins/workspace/joyent-org_sdc-booter_PR-5]# git diff
diff --git a/package.json b/package.json
index 85086b6..a2580b7 100644
--- a/package.json
+++ b/package.json
@@ -13,7 +13,7 @@
     "jsprim": "2.0.0",
     "mkdirp": "0.5.0",
     "node-uuid": "1.2.0",
-    "pack":  "file:build/pack-0.0.1.tgz",
+    "pack": "file:build/pack-0.0.1.tgz",
     "restify": "4.3.0",
     "sdc-bunyan-serializers": "git+https://github.com/joyent/sdc-bunyan-serializers.git#a3e7780",
     "sdc-clients": "10.3.0",
```

Hrm. What new step is re-writing package.json?

Also TIL about a "file:..." local package dependency in package.json.

**Comment by trentm** [comment]
That "pack" dep was added recently:

```
commit 839c54eb0362274da4e6ff340931d0bd4bd93ca1 (origin/release-20190718)
Author: Chris Burroughs <chris.burroughs@joyent.com>
Date:   2019-07-01T14:50:20-04:00 (4 months ago)

    TRITON-1750 booter should use node v6
    TRITON-1751 update booter base image to triton-origin-x86_64-18.4.0
    Reviewed by: Rui <rui@joyent.com>
    Approved by: Rui <rui@joyent.com>

diff --git a/package.json b/package.json
index 72d9c40..85086b6 100644
--- a/package.json
+++ b/package.json
@@ -1,7 +1,7 @@
 {
   "name": "booter",
   "description": "DHCP server for booting SDC compute nodes",
-  "version": "1.4.0",
+  "version": "1.5.0",
   "author": "Joyent (joyent.com)",
   "private": true,
   "dependencies": {
@@ -13,12 +13,13 @@
     "jsprim": "2.0.0",
     "mkdirp": "0.5.0",
     "node-uuid": "1.2.0",
+    "pack":  "file:build/pack-0.0.1.tgz",
```

**Comment by trentm** [comment]
It is the `make test` that results in package.json being rewritten (really it is the build steps that the `test` target depends on), and then `git clean -fdx` doesn't revert those changes, so we get:

```
[root@trent-builder-18 ~/joy/sdc-booter]# git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package.json

no changes added to commit (use "git add" and/or "git commit -a")
```

before starting the build.

**Comment by trentm** [comment]
If we change to `npm install --no-save` I think that prevents it.

**Comment by trentm** [comment]
I'm waiting on https://github.com/joyent/sdc-booter/pull/9 which should fix the build error here, then I'll approve this one.

**Comment by timfoster** [comment]
> I'm waiting on #9 which should fix the build error here, then I'll approve this one.

(just a note to say I added comments to #9, wondering whether we might use an easier approach for that change)

**Comment by trentm** [comment]
Okay, https://jenkins.joyent.us/job/joyent-org/job/sdc-booter/job/PR-5/3/console shows that the `npm install --no-save` fixes the "package.json was changed" issue without us having to tweak package.json to conform.  I'll now remove that errant space in package.json to be neat and tidy.

**Pull request merged**
